base code initial commit
modulabs/Meani.mo.Vision pull request #1
Opened 2019-08-19 19:36 UTC by kooock

map.py가 main access point입니다.  실행커멘드는 python map.py 드론이미지경로 라이다이미지경로 결과출력파일경로 입니다. 예) python map.py img/image1.jpg img/case1.jpg img/result.jpg

opencv 버전은 3.4.2입니다. 

다음 사항은 제가 자고 일어나서 md파일로 올리겠습니다.

2019-08-20 05:42 UTC, pep8speaks commented
Hello @kooock! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`featureDetector.py`](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py):

> [Line 3:1](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L3): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 5:22](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L5): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 5:32](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L5): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 5:43](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L5): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 5:53](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L5): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 17:19](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L17): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 20:28](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L20): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 24:80](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L24): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 24:114](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L24): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 25:80](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L25): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 25:114](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L25): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 27:40](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/featureDetector.py#L27): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

* In the file [`histogram.py`](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py):

> [Line 5:34](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L5): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:5](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L11): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 11:34](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:38](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:43](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:49](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:52](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 12:10](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:16](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 22:7](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/histogram.py#L22): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator

* In the file [`imageLoader.py`](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/imageLoader.py):

> [Line 5:1](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/imageLoader.py#L5): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 7:22](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/imageLoader.py#L7): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 7:37](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/imageLoader.py#L7): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 18:30](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/imageLoader.py#L18): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 21:5](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/imageLoader.py#L21): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 21:22](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/imageLoader.py#L21): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 28:23](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/imageLoader.py#L28): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`map.py`](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map.py):

> [Line 14:1](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 14:32](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map.py#L14): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 17:5](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map.py#L17): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 17:39](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map.py#L17): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 23:5](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map.py#L23): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 23:47](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map.py#L23): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 25:14](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map.py#L25): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 29:5](https://github.com/modulabs/Meani.mo.Vision/blob/40ab4be60fcb0dd7bd1d7d3386442df2c062b8e1/map. [...]

2019-08-20 05:47 UTC, visionNoob commented
엄격하진 않더라도 
기본적인 coding convention 이 있어야 할 것 같습니다. 
우선적으로 [python PEP8](https://www.python.org/dev/peps/pep-0008/) 
을 따르는게 어떠신지요? 제가 이 PR에 예시를 올려놨는데 
선택한 github repo에 올라오는 PR 코드가 PEP8을 따르지 않으면 자동으로 블락되게 할 수 도 있습니다.

2019-08-20 05:47 UTC, visionNoob commented
기본적인 코딩컨벤션은 코드를 유지보수하는 비용을 줄이는데 아주 많은 도움이 될 것 같습니다. 
다 같이 한번 고민해보면 좋을 것 같습니다.

2019-08-20 06:27 UTC, kooock commented
저도,그게 좋다고 샌각합니다 
PEP8을 맞춰보겠습니다.

2019-08-20 06:29 UTC, visionNoob requested changes

2019-08-20 06:29 UTC, visionNoob commented on map.py
> +    registration(sys.argv[1], sys.argv[2], sys.argv[3])
sys.argv 대신 arg_parser 를 이용하는게 어떨까요?

2019-08-20 06:29 UTC, visionNoob commented on map.py
> +    feature_detector = FeatureDetector(drone_img,"SIFT",lidar_img,"SIFT")
향후 확장성을 위해서 각 도메인(drone_image, lidar_image)의 
feature detector를 분리시켜도 될 것 같습니다. 
가령 
drone_feature_detector = FeatureDetector(drone_img, "SIFT")
lidar_feature_detector = FeatureDetector(lidar_img, "SIFT")

drone_features = drone_feature_detector.get_feature_and_descriptor()
lidar_features = lidar_feature_detector.get_feature_and_descriptor()

2019-08-20 06:29 UTC, visionNoob commented on matcher.py
> +    def find_homography(self):
Matcher class에 
find_homography 함수가 있는게 조금 이상합니다. 
직관적으로 Matcher 라는 클래스 이름을 보면 
두 특징 간의 matching pair를 만들겠구나? 정도의 느낌이거든요(제가 느끼기에는)

2019-08-20 06:29 UTC, visionNoob commented on matcher.py
> +        cv2.imwrite(file_name,img3)
draw 함수는 이름만보면 
입력 이미지에 매칭 포인트를 "그려만" 주는 함수인 것 같아 보이는데
거기에 추가적으로 show 와 imwite 까지 수행하는 것 같습니다.

2019-08-20 06:29 UTC, visionNoob commented on preprocessor.py
> +        #TODO
이부분은 TODO 인가요?
TODO의 내용이 없어서 모르겠습니다..

2019-08-20 20:46 UTC, JaeHyeokLee commented on matcher.py
> +        cv2.imwrite(file_name,img3)
@visionNoob 이 부분은 괜찮은 것 같습니다. 다만, 이미지 저장 여부를 save_img=True 와 같이 함수의 인자로 주는 형식도 좋을 것 같습니다.

2019-08-20 20:50 UTC, JaeHyeokLee commented on matcher.py
> +    def find_homography(self):
@visionNoob 일단 Homography를 찾아서 매칭을 하는 방식이니 Matcher class 안에 method 로 선언하는건 문제없어 보입니다 ㅎㅎ

2019-08-20 20:58 UTC, JaeHyeokLee commented on map.py
> +
@visionNoob 아래의 find_homography 함수 이름이 클래스 이름과 매치가 되지 않는다고 생각되시면, Matcher class 안에 
def match(self):
    self.extract_match()
    self.find_homography()
    self.draw_matches()
처럼 만들어놓고 main 함수 안에서는 matcher.match() (또는 matcher.forward() )
와 같이 코드를 짜는 경우도 본 것 같습니다 ㅎㅎ (코드 논리적으로 급하게 바꿔야 할 사항은 아니니 더 좋은 코드를 위해서 같이 논의해보면 좋을 것 같습니다 ㅎㅎ)

2019-08-20 21:02 UTC, JaeHyeokLee commented
코드 내부에서 논리적으로 큰 오류는 없어 보입니다.
다만, 제가 잘 몰라서 그러는데 이 레포가 오픈되어 있는 레포인가요?
이 레포가 오픈되어 있는 레포라면 저희 샘플 데이터 올려도 되는걸까요??
(아니라면 죄송합니다 ㅎㅎ)

2019-08-20 21:05 UTC, JaeHyeokLee approved these changes

2019-08-20 22:59 UTC, kooock commented
어?! 그러네요  이미지 빼야겠네요

2019-08-23 14:00 UTC, visionNoob approved these changes

2019-08-23 14:00 UTC, merged